'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import FormContextProvider from "@/contexts/formContext";
import { IoChevronBack } from "react-icons/io5";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <FormContextProvider>

      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/bg_2.webp')] bg-cover bg-center min-h-screen flex flex-col`}
        >

          <div className="min-h-screen backdrop-blur-sm">
            <header className="h-20 px-4 py-2">
              <Link href="/">
                <Image
                  className=" "
                  src="/ican_logo.png"
                  alt="Vercel logomark"
                  width={84}
                  height={52}
                  priority
                />
              </Link>
            </header>
            {/* <div className="flex items-center h-6 px-4 py-2  w-fit cursor-pointer" onClick={() => window.history.back()}>
              <IoChevronBack className="text-white h-4 w-4" />
              <p className="text-white ml-1 text-md">Back</p>
            </div> */}
            {children}
          </div>
        </body>
      </html>
    </FormContextProvider>
  );
}
